/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build process.
precacheAndRoute(self.__WB_MANIFEST);

const DB_NAME = 'notely-db';
const NOTES_STORE = 'notes';
const AUTH_STORE = 'auth';
const SYNC_URL = '/api/notes/sync';

// ──────────────────────────────────────────────
// Minimal IndexedDB helpers (no library deps)
// ──────────────────────────────────────────────
function openDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, 3);
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
    req.onupgradeneeded = (e) => {
      const db = (e.target as IDBOpenDBRequest).result;
      if (!db.objectStoreNames.contains(NOTES_STORE)) {
        db.createObjectStore(NOTES_STORE, { keyPath: 'id', autoIncrement: true });
      }
      if (!db.objectStoreNames.contains('pages')) {
        db.createObjectStore('pages', { keyPath: 'id', autoIncrement: true });
      }
      if (!db.objectStoreNames.contains(AUTH_STORE)) {
        db.createObjectStore(AUTH_STORE);
      }
    };
  });
}

function dbGet<T>(db: IDBDatabase, store: string, key: IDBValidKey): Promise<T | undefined> {
  return new Promise((resolve, reject) => {
    const req = db.transaction(store).objectStore(store).get(key);
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

function dbGetAll<T>(db: IDBDatabase, store: string): Promise<T[]> {
  return new Promise((resolve, reject) => {
    const req = db.transaction(store).objectStore(store).getAll();
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

function dbPut(db: IDBDatabase, store: string, value: any): Promise<void> {
  return new Promise((resolve, reject) => {
    const req = db.transaction(store, 'readwrite').objectStore(store).put(value);
    req.onsuccess = () => resolve();
    req.onerror = () => reject(req.error);
  });
}

function dbDelete(db: IDBDatabase, store: string, key: IDBValidKey): Promise<void> {
  return new Promise((resolve, reject) => {
    const req = db.transaction(store, 'readwrite').objectStore(store).delete(key);
    req.onsuccess = () => resolve();
    req.onerror = () => reject(req.error);
  });
}

// ──────────────────────────────────────────────
// Background Sync
// ──────────────────────────────────────────────
self.addEventListener('sync', (event: any) => {
  if (event.tag === 'sync-notes') {
    event.waitUntil(syncNotes());
  }
});

async function syncNotes() {
  try {
    const db = await openDB();

    const token = await dbGet<string>(db, AUTH_STORE, 'token');
    if (!token) {
      console.warn('[SW] No auth token, skipping sync');
      return;
    }

    const allNotes = await dbGetAll<any>(db, NOTES_STORE);
    const pending = allNotes.filter(
      n => n.syncStatus === 'pending' || n.syncStatus === 'deleted' || n.syncStatus === 'error'
    );

    if (pending.length === 0) return;
    console.log(`[SW] Syncing ${pending.length} notes...`);

    for (const note of pending) {
      try {
        const response = await fetch(SYNC_URL, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`,
          },
          body: JSON.stringify(note),
        });

        if (response.ok) {
          const result = await response.json();
          if (note.syncStatus === 'deleted') {
            await dbDelete(db, NOTES_STORE, note.id);
          } else {
            await dbPut(db, NOTES_STORE, {
              ...note,
              syncStatus: 'synced',
              remoteId: result.remoteId ?? note.remoteId,
              syncError: undefined,
            });
          }
        } else if (response.status === 401) {
          await dbPut(db, NOTES_STORE, { ...note, syncStatus: 'error', syncError: 'Unauthorized' });
          break; // stop — token is invalid
        } else {
          const msg = await response.text();
          await dbPut(db, NOTES_STORE, { ...note, syncStatus: 'error', syncError: msg });
        }
      } catch (err) {
        await dbPut(db, NOTES_STORE, { ...note, syncStatus: 'error', syncError: 'Network error' });
      }
    }
  } catch (err) {
    console.error('[SW] Sync process failed:', err);
  }
}

// ──────────────────────────────────────────────
// Push Notifications
// ──────────────────────────────────────────────
self.addEventListener('push', (event) => {
  const data = event.data ? event.data.json() : {};
  const { title = 'Notely', body = 'Bạn có thông báo mới' } = data;

  event.waitUntil(
    self.registration.showNotification(title, {
      body,
      icon: '/icons/icon-192.png',
      badge: '/icons/icon-192.png',
    })
  );
});

// Notification click → focus/open the app
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(clients => {
      const existing = clients.find(c => c.url.includes(self.location.origin));
      if (existing) return existing.focus();
      return self.clients.openWindow('/');
    })
  );
});
