version: '3.8'

services:
  notely-app:
    image: node:20-alpine
    volumes:
      - ./client:/app
    working_dir: /app
    environment:
      - NODE_ENV=production
    command: sh -c "npm install && npm run build && npm run preview -- --host --port 5173"

  notely-api:
    image: node:20-alpine
    volumes:
      - ./server:/app
    working_dir: /app
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/notely
      - PORT=3000
    command: sh -c "npm install && npm start"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - notely-app
      - notely-api

volumes:
  mongodb_data:
