/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST);

// Add custom service worker logic here (e.g., Push Notification handlers)
self.addEventListener('push', (event) => {
  const data = event.data ? event.data.json() : {};
  const { title, body } = data;

  event.waitUntil(
    self.registration.showNotification(title || 'Notely', {
      body: body || 'New notification',
      icon: '/icons/icon-192.png',
    })
  );
});
